[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8.0", features = ["runtime-tokio-native-tls", "sqlite"]}
dotenv = "0.15.0"
