[package]
name = "web_service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
tokio = { version = "1.39.2", features = ["full"] }
axum-server = "0.7.1"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
